@host = https://localhost:7140

POST {{host}}/api/authentication/register
Content-Type: application/json

{
    "firstname":"153",
    "lastname":"123",
    "email":"exampleemail@emailservice.com",
    "password":"123456"
}
