@host = https://localhost:7140
@personId = cd3e5fc5-2a88-44fd-aed6-095965df4635
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGQyYzdlMS1kOGVmLTQ0ODAtOTViMC1jZjBhMjdlNzdjZjUiLCJnaXZlbl9uYW1lIjoiMTUzIiwiZmFtaWx5X25hbWUiOiIxMjMiLCJqdGkiOiJhODhmMzQ2ZS0wZTFiLTQzYWQtYjlkYi03OGQ4MGFjZGY2ZTAiLCJleHAiOjE3MDEzOTM2NDksImlzcyI6Ik1lbWJlckluZm9NZW1iZXJJbmZvIiwiYXVkIjoiTWVtYmVySW5mbyJ9.bsBxxQzdyoQcogFYpF_pA4kFBk-IeXM70GCCcSHxFQI

POST https://localhost:7140/products/createProduct
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "ProductName": "3 Months Subscription",
    "Price": [
        {
            "Amount": 1200,
            "Currency": "USD"
        }
    ],
    "Months": 3
}