@host = https://localhost:7140
@personId = cd3e5fc5-2a88-44fd-aed6-095965df4635
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTc5YWNiYy05NDBhLTQ5MjMtOGQ0MC0zNWE0NmZhODVmNDgiLCJnaXZlbl9uYW1lIjoiMTUzIiwiZmFtaWx5X25hbWUiOiIxMjMiLCJqdGkiOiI1YTMxODNmNS1iOGFmLTRhMTYtOTliNi1lODRiZWY0NDJmNWQiLCJleHAiOjE2OTg3MDc2MTEsImlzcyI6Ik1lbWJlckluZm9NZW1iZXJJbmZvIiwiYXVkIjoiTWVtYmVySW5mbyJ9.hP3y8z2Ho9Ra-_LZor1u30GuxDB9bBLt_NBUoWoBYc8

POST https://localhost:7140/products
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "ProductName": "Product 2",
    "Price": [
        {
            "Amount": 10123150,
            "Currency": "USD"
        }
    ],
    "Months": 12,
    "PersonIds": [
        {
            "Id": "cd3e5fc2-2a88-44fd-aed6-0959652f4635"
            //if id is different add inside the array
            //get product
        }
    ]
}